config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy]
   # users routes
  get "/signup", to: "users#new"
  get "/profile", to: "users#show"
  # get '/users/edit', to: "users#edit"

  get "/about", to: "pages#about"

  # sessions routes
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  # post "/sessions", to: "sessions#create"
  resources :sessions

  resources :maps
  root "pages#home"
end

#       Prefix Verb   URI Pattern                  Controller#Action
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user GET    /users/:id(.:format)         users#show
#              PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#       signup GET    /signup(.:format)            users#new
#      profile GET    /profile(.:format)           users#show
#        about GET    /about(.:format)             pages#about
#        login GET    /login(.:format)             sessions#new
#       logout GET    /logout(.:format)            sessions#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PATCH  /sessions/:id(.:format)      sessions#update
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy
#         maps GET    /maps(.:format)              maps#index
#              POST   /maps(.:format)              maps#create
#      new_map GET    /maps/new(.:format)          maps#new
#     edit_map GET    /maps/:id/edit(.:format)     maps#edit
#          map GET    /maps/:id(.:format)          maps#show
#              PATCH  /maps/:id(.:format)          maps#update
#              PUT    /maps/:id(.:format)          maps#update
#              DELETE /maps/:id(.:format)          maps#destroy
#         root GET    /                            pages#home

app/models/map.rb
class Map < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :maps, dependent: :destroy

  validates :email, :presence => true, uniqueness: true
  validates :password_digest, :presence => true, confirmation: true

  has_attached_file :profile_image,
                    :styles => { :medium => "200x200#" },
                    :storage => :s3,
                    :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
                    :s3_host_name => 's3-us-west-1.amazonaws.com',
                    :path => "profile_image/:id/:style/profile_image.:extension",
                    :default_url => "/default-profile.png"


  def s3_credentials
   { :bucket => ENV["S3_BUCKET"], :access_key_id => ENV["S3_PUBLIC_KEY"], :secret_access_key => ENV["S3_SECRET"] }
  end

  validates_attachment :profile_image,
                       :content_type => { :content_type => ["image/jpeg", "image/jpg", "image/gif", "image/png"] },
                       :size => { :in => 0..7000.kilobytes }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    unless current_user
      redirect_to login_path
    end
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def new
    render :new
  end

  def create
    @map = current_user.maps.new(map_params)
    if @map.save
      render json: @map
    else
      flash[:error] = "Oops! Try saving your map again."
      render json: { errors: @map.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @map = Map.find_by(params[:id])
    render json: @map
  end

  def edit
    map_id = params[:id]
    @map = Map.find(map_id)
  end

  def update
    map_id = params[:id]
    map = Map.find(map_id)
    update_params = params.require(:map).permit(:title)
    if map.update_attributes(update_params)
      redirect_to profile_path
      flash[:success] = "Map successfully updated!"
    else
      redirect_to profile_path
      flash[:error] = "Oops! Try updating again!"
    end
  end

  def destroy
    Map.find(params[:id]).destroy
    redirect_to profile_path
  end

  private
    def map_params
      params.require(:map).permit(:user_id, :to, :from, :measurement, :travel_mode, :title, :url)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to profile_path
    else
      render :new
    end
  end

  def create
    user_params = params.require(:user)
    user = User.find_by_email(user_params[:email])

    # If the user exists AND the password entered is correct.
    if user && user.authenticate(user_params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to profile_path
    else
      # If user's login doesn't work, send them back to the login form.
      flash[:error] = "Oops! Check your email and password and try again!"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, only: [:show]

  def index
  end

  def new
    if current_user
      redirect_to profile_path
    else
      @user = User.new
      render :new
    end
  end

  def create
    if current_user
      redirect_to profile_path
    else
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to profile_path
      else
        flash[:error] = "Oops! Try again to save your account!"
        redirect_to signup_path
      end
    end
  end

  def show
    @maps = current_user.maps.order(created_at: :desc).page(params[:page]).per(10)
  end

  def edit
  end

  def update
    if current_user
      form_params = params.require(:user).permit(:first_name, :last_name, :user_name, :email, :about, :profile_image)
      current_user.update_attributes(form_params)
      redirect_to profile_path
      # flash[:success] = "Profile successfully updated!"
    else
      redirect_to '/'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>EverestApp</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- font awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<!-- top navbar -->
  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/">EVEREST</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if current_user %>
              <a href="/logout" class="btn">Log Out</a>
            <% else %>
            <li>
              <a href="/login" class="btn">Log In</a>
            </li>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/about">About</a></li>
              <li><a href="/profile">Profile</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <!-- top navbar end -->

	<%= yield %>

<%= javascript_include_tag 'application' %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>

</body>
</html>

app/views/maps/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
	<h1>Edit Map Title</h1>
	<hr>
	<%= form_for @map do |f| %>
	<div class="form-group">
		<!-- Enables flash messages within the form for superior UX -->
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-notice'}" %>
		<% end %>

		<%= f.text_field :title, placeholder: "Title", class: "form-control" %><br>
		<%= f.submit "Update Title", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>
<div class="col-md-4"></div>

app/views/maps/new.html.erb
This is the new page.

app/views/pages/about.html.erb
<div class="container-fluid about-section">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2"></div>
      <div class="col-md-8 about">
        <h1 class="text-center logo">EVEREST</h1>
        <p>As technology brings our world closer together, our lives become more fast-paced, require more travel and more routes to our ever-changing destinations. Whether you are on your way home from work, going on an early morning run, hopping on your bike for that next rush, or simply going on a walk for some out-of-office Zen, there are hills to embrace, avoid, or explore. Pick your destination, adjust the route for more or less elevation, and save your routes for next time. Everest empowers city-dwellers to choose their elevation routes for what ever their day may bring.</p>
        <p>Everest is brought to you by a team of Full-Stack Web Developers at General Assembly. General Assembly transforms thinkers into creators through education and opportunities in technology, business, and design.
        </p>
      </div>
      <div class="col-md-2"></div>
    </div> <!-- close col-md-8 col-md-offset-2 -->
  </div> <!-- close .row -->

  <hr>
  <!-- Team member photos and links to github etc -->
  <div class="col-md-12 row authors">
    <h1 class="text-center">This app was created with love by:</h1>
    <div class="col-md-3" style="border-right: 1px solid #ccc;">
      <img class="portrait img-circle img-responsive center-block" src="/about-img/everest_1.jpg">
      <br />
      <h4>Aubrey<h4>
        <a class="" href="https://github.com/aubreyworley" target="_blank">
          <i class="fa fa-github-square"></i>
        </a>
        <a class="" href="https://www.linkedin.com/in/aubreyworley" target="_blank">
          <i class="fa fa-linkedin-square"></i>
        </a>
        <p>When Aubrey isn’t busy creating and thinking of her next business plan, she’s exploring other worlds in her never-ending book list or adventuring in the great outdoors. </p>
      </div> <!-- close .col-md-3 -->
      <div class="col-md-3" style="border-right: 1px solid #ccc;">
        <img class="portrait img-circle img-responsive center-block" src="/about-img/everest_2.jpg">

        <br />

        <h4>Brennan<h4>
          <a class="" href="https://github.com/bgamwell" target="_blank">
            <i class="fa fa-github-square"></i>
          </a>
          <a class="" href="https://www.linkedin.com/in/brennangamwell" target="_blank">
            <i class="fa fa-linkedin-square"></i>
          </a>
          <p>Brennan is a programmer, marketer and writer. When he's not building websites, he's likely reading or on an urban hike in hilly San Francisco.</p>
          <!-- picture and bio -->
        </div> <!-- close .col-md-3 -->
        <div class="col-md-3" style="border-right: 1px solid #ccc;">
          <img class="portrait img-circle img-responsive center-block" src="/about-img/everest_3.jpg">
          <br />
          <h4>Davina<h4>
            <a class="" href="https://github.com/lilvina" target="_blank">
              <i class="fa fa-github-square"></i>
            </a>
            <a class="" href="https://www.linkedin.com/in/davinataylor" target="_blank">
              <i class="fa fa-linkedin-square"></i>
            </a>
            <p>Davina spends her free time immersing herself in anime, books, and the software developer community. She’s passionate about local learning opportunities for African Americans and loves to express herself through dancing on stage.</p>
            <!-- picture and bio -->
          </div> <!-- close .col-md-3 -->
          <div class="col-md-3">
            <img class="portrait img-circle img-responsive center-block" src="/about-img/everest_4.jpg">
            <br />
            <h4>Erin<h4>
              <a class="" href="https://github.com/erintherad" target="_blank">
                <i class="fa fa-github-square"></i>
              </a>
              <a class="" href="https://www.linkedin.com/in/erinmahoneyphoto" target="_blank">
                <i class="fa fa-linkedin-square"></i>
              </a>
              <p>Erin is passionate about photography and good web design.  She avidly seeks the flattest routes to run in San Francisco and newest food spots to nom.</p>
              <!-- picture and bio -->
            </div> <!-- close .col-md-3 -->
          </div> <!-- close .row -->

          <!-- Information about our stack -->
          <div class="row" id="stack">
            <hr>
            <div class="col-md-12 logos text-center">
              <h1>This app is made possible by:</h1>
              <!-- Stack logos will be placed here: Rails, GoogleAPI, Postgres -->
              <!-- Link to Stack Share blog post (stretch if time on Thursday night) -->
              <span><a href="https://developers.google.com/maps/?hl=en" target="_blank"><img class="tech" src="/logos/google-developers-logo.png"></a></span>
              <span><a href="http://rubyonrails.org/" target="_blank"><img class="tech" src="/logos/ruby-on-rails.png"></a></span>
              <span><a href="https://aws.amazon.com/s3/" target="_blank"><img class="tech" src="/logos/s3.jpg"></a></span>
              <span><a href="http://www.postgresql.org/" target="_blank"><img class="tech" src="/logos/postgresql-logo.png"></a></span>
            </div>
          </div>
        </div> <!-- close .container-fluid -->

app/views/pages/home.html.erb
   <div class="col-md-12 header-title" id="landing-img">
    <div class="container-fluid">
      <h1 class="logo" id="site-title">EVEREST</h1>
      <h2 class="tag-line header-title-hgroup" id="tagline">Elevate your route</h2>
    </div>
  </div>

  <!-- Tutorial section -->
  <div class="container-fluid tutorial">
    <div class="row text-center">
      <h2 class="about-tag">How <span class="about-logo">EVEREST</span> works:</h2>
    </div>
    <div class="row about text-center">
      <div class="col-md-4 about-one">
        <img src="/gifs/making.gif">
        <h3>1</h3>
        <p>
          Choose your destination and travel mode.
        </p>
      </div>
      <div class="col-md-4 about-two">
        <img src="/gifs/dragging.gif">
        <h3>2</h3>
        <p>
          Customize your elevation.
        </p>
      </div>
      <div class="col-md-4 about-three">
        <img src="/gifs/saving.gif">
        <h3>3</h3>
        <p>
          Save your route for next time.
        </p>
      </div>
    </div>
  </div>
  <!-- End of tutorial section -->

  <div class="container-fluid" id="scroll">
    <div class="map">
      <div class="col-md-12">
       <div class="nav-header">
        <h1>CREATE YOUR ROUTE:</h1>
      </div>
      <div>
        <form class="form-inline" id="routes">
          <div class="map-nav">
            <div class="form-group">
              <label>
                From: <input id="from" type="text" placeholder="Nob Hill, San Francisco, CA">
              </label>
            </div>
            <div class="form-group" id="from-to-switcher"></div>
            <div class="form-group">
              <label>
                To: <input id="to" type="text" placeholder="Russian Hill, San Francisco, CA">
              </label>
            </div>
            <div class="form-group">
              <label for="travel-mode">Travel mode:</label>
              <select id="travel-mode">
                <option>Bicycling</option>
                <option>Walking</option>
                <option>Driving</option>
              </select>
            </div>
            <div class="form-group">
              <label for="measurement-mode">Units:</label>
              <select id="measurement-mode">
                <option value="miles">Miles</option>
                <option value="km">Kilometres</option>
              </select>
            </div>
            <div class="form-group">
              <button class="btn btn-dark" id="go">Go</button>
            </div>
            <% if current_user %>
            <div class="hidden form-group" id="save">
              <a href="#" data-toggle="modal" data-target="#saveModal"><label>Save your route?</label></a>
              <% end %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Save your route</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <div>
                <span>From: <input class="form-control" id="from-pop" type="text" placeholder="Nob Hill, San Francisco, CA"></span>
            </div>
            <div>
                <span>To: <input class="form-control" id="to-pop" type="text" placeholder="Russian Hill, San Francisco, CA"></span>
            </div>
            <div>
              <span for="travel-mode-pop">Travel mode:</span>
              <select class="form-control" id="travel-mode-pop">
                <option>Bicycling</option>
                <option>Walking</option>
                <option>Driving</option>
              </select>
            </div>
            <div>
              <span for="measurement-mode-pop">Units:</span>
              <select class="form-control" id="measurement-mode-pop">
                <option value="miles">Miles</option>
                <option value="km">Kilometres</option>
              </select>
            </div>
            <div>
                <span>Title: <input class="form-control" id="title-pop" type="text" placeholder="My running route"></span>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" id="save-changes" class="btn btn-primary">Save changes</button>
        <br>
        <br>
        <p id="save-alert" class="hidden text-center">Your map has been saved to your <a href="/profile">profile page</a>.</p>
      </div>
    </div>
  </div>
</div>

<div class="col-md-12 charts">
  <div class="col-md-6 map-canvas-container">
    <div>
      <div id="map-canvas"></div>
      <div class="social">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
     fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-share-button" data-href="http://everest-app.herokuapp.com" data-layout="button"></div>
    <a class="btn-twitter btn-lg"
   href="https://twitter.com/share?url=http://everest-app.herokuapp.com/&amp;text=Elevate your route: ">
  <i class="fa fa-twitter"></i></a>
  </div>
    </div>
  </div>
  <div class="col-md-2 table-con footer">
    <table class="table">
      <th>
        <td>Difficulty</td>
        <td>% Grade</td>
      </th>
      <tr>
        <td><div class="color-index" id="green"</div></td>
        <td>Easy</td>
        <td>&lt;5%</td>
      </tr>
      <tr>
        <td><div class="color-index" id="yellow"</div></td>
        <td>Moderate</td>
        <td>5-10%</td>
      </tr>
      <tr>
        <td><div class="color-index" id="blue"</div></td>
        <td>Difficult</td>
        <td>10-15%</td>
      </tr>
      <tr>
        <td><div class="color-index" id="red"</div></td>
        <td>Very Difficult</td>
        <td>15-20%</td>
      </tr>
      <tr>
        <td><div class="color-index" id="black"</div></td>
        <td>Too *wheeze* steep</td>
        <td>&gt;20%</td>
      </tr>
    </table>
    <div class="labels">
      Distance:
      <span id="distance"></span>
    </div>
    <div class="labels">
      Travel Time:
      <span id="travel-time"></span>
    </div>
  </div>
  <div class="col-md-3">
    <div class="row">
      <div>
        <div id="elevation_chart"></div>
        <div id="slope_chart"></div>
      </div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>
<!-- <div id="directionsPanel"></div>
<div class="row" id="author">
</div> -->

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDXj3FxJkwYjszaD_xk5c_l8CAqjCRfno4"></script>

<!-- link to themed version of bootstrap hosted on the internet -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

app/views/users/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
  <h1>Edit Profile</h1>
  <hr>
  <%= form_for current_user, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <!-- Enables flash messages within the form for superior UX -->
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-notice'}" %>
      <% end %>
  
      <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %><br>
      <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %><br>
      <%= f.text_field :user_name, placeholder: "User Name", class: "form-control" %><br>
      <%= f.email_field :email, placeholder: "Email", class: "form-control" %><br>
      <%= f.text_area :about, placeholder: "About Me", class: "form-control" %><br>
      <%= f.file_field :profile_image, class: "btn" %><br>
      <%= f.submit "Save Profile", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="col-md-4"></div>

app/views/users/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
	<h3> Sign Up </h3>
	<hr>
	<%= form_for @user, :html => {:id => "signup-form"} do |f| %>
	<div class="form-group">

    <!-- Enables flash messages within the form for superior UX -->
		<% flash.each do |name, msg| %>
	    <%= content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-notice'}" %>
	  <% end %>

	  <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
	</div>
	<div class="form-group">
	  <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
	</div>
	  <%= f.submit "Sign Up", class: "btn btn-primary" %>
	<% end %>
	</div>
<div class="col-md-4"></div>

app/views/users/show.html.erb
<div class="profile-page">
  <div class="jumbotron"></div>
  <div class="container-fluid">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <p><%= image_tag current_user.profile_image.url(:medium), class: "img-responsive img-rounded profile-img" %></p>
      <div class="profile-info">
        <h2><%= current_user.first_name %><%= " " %><%= current_user.last_name %></h2>
        <p><%= @current_user.user_name %></p>
        <p>Joined <%= @current_user.created_at.strftime("%b. %Y") %></p>
        <p><%= @current_user.about %></p>
      </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6">
      <span class="profile-welcome">Welcome <%= current_user.first_name %>!
        <span><%= link_to "update profile", edit_user_path(current_user), class: "btn btn-dark pull-right" %></span>
      <p><%= paginate @maps %></p>
    <% @maps.each do |map| %>
    <div class="map-section">
      <div class="dropdown pull-right">
        <button class="dropdown-toggle button btn btn-dark" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Edit post
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><%= link_to "Update Map", edit_map_path(map) %></li>
          <li><%= link_to "Delete", map, method: :delete %></li>
        </ul>
      </div>
      <span class="post-header"><%= map.title %></span><br>
      <hr>
      <span class="post-header">From: <span class="post-body"><%= map.from %></span><br>
      <span class="post-header">To: <span class="post-body"><%= map.to %></span><br>
      <span class="post-header">Travel Mode: <span class="post-body"><%= map.travel_mode %></span><br>
      <span class="post-header">Measurement: <span class="post-body"></h3><%= map.measurement %></span><br>
      <hr>
      <span class="post-header"><%= link_to "See Your Route", map.url %></span><br>
    </div>
    <% end %>
  </div>
  <div class="col-md-1"></div>
</div>
</div>